
const images = [
  {
    "title": "Boat On The Huon River Reflection",
    "url": "https://files.jacobsamo.com/photography/boat-on-the-huon-river-reflection.webp",
    "alt": "Sailing boat on the Huon River, Tasmania",
    "width": 1407,
    "height": 2048,
    "aspectRatio": 0.69,
    "format": "webp",
    "fileSize": 84134,
    "fileName": "boat-on-the-huon-river-reflection.webp",
  },
  {
    "title": "Antonio Lazarus Bike Tour Jsamophotography",
    "url": "https://files.jacobsamo.com/photography/antonio_lazarus-bike-tour-jsamophotography.webp",
    "alt": "Antonio Lazarus giving a tour around Brisbane's street art, BSAF",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 144170,
    "fileName": "antonio_lazarus-bike-tour-jsamophotography.webp",
  },
  {
    "title": "2 Butterflys",
    "url": "https://files.jacobsamo.com/photography/2-butterflys.webp",
    "alt": "Two blue butterflies",
    "width": 2048,
    "height": 1363,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 68366,
    "fileName": "2-butterflys.webp",
  },
  {
    "title": "Element Photography Jsamo Photography",
    "url": "https://files.jacobsamo.com/photography/element-photography-jsamo_photography.webp",
    "alt": "Lachie from Element Photography, on Stradbroke board walk",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 265024,
    "fileName": "element-photography-jsamo_photography.webp",
  },
  {
    "title": "Black White Butterflys",
    "url": "https://files.jacobsamo.com/photography/black-white-butterflys.webp",
    "alt": "Black silhouettes of butterflies streaming through window",
    "width": 2048,
    "height": 1403,
    "aspectRatio": 1.46,
    "format": "webp",
    "fileSize": 60112,
    "fileName": "black-white-butterflys.webp",
  },
  {
    "title": "Foggy Morning",
    "url": "https://files.jacobsamo.com/photography/foggy-morning.webp",
    "alt": "Foggy road with road markers ahead",
    "width": 2048,
    "height": 1363,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 113746,
    "fileName": "foggy-morning.webp",
  },
  {
    "title": "Fire Disk",
    "url": "https://files.jacobsamo.com/photography/fire-disk.webp",
    "alt": "Glowing fire disk spinning galaxy",
    "width": 2048,
    "height": 1363,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 109734,
    "fileName": "fire-disk.webp",
  },
  {
    "title": "Fire Sprials",
    "url": "https://files.jacobsamo.com/photography/fire-sprials.webp",
    "alt": "Glowing orange fire spiral lines abstract",
    "width": 2048,
    "height": 1363,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 205760,
    "fileName": "fire-sprials.webp",
  },
  {
    "title": "Ladies Face Drapl",
    "url": "https://files.jacobsamo.com/photography/ladies-face-drapl.webp",
    "alt": "Woman with blue tinted face painted by Drapl",
    "width": 1659,
    "height": 2048,
    "aspectRatio": 0.81,
    "format": "webp",
    "fileSize": 211702,
    "fileName": "ladies-face-drapl.webp",
  },
  {
    "title": "Mesume Books Fly",
    "url": "https://files.jacobsamo.com/photography/mesume-books-fly.webp",
    "alt": "Books flying through golden light.",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 427032,
    "fileName": "mesume-books-fly.webp",
  },
  {
    "title": "Mc Battlesandjams Jsamophotography",
    "url": "https://files.jacobsamo.com/photography/mc-battlesandjams-jsamophotography.webp",
    "alt": "MC on stage at Battles and Jam's",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 352560,
    "fileName": "mc-battlesandjams-jsamophotography.webp",
  },
  {
    "title": "River Fire",
    "url": "https://files.jacobsamo.com/photography/river-fire.webp",
    "alt": "Brisbane River Fire",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 33196,
    "fileName": "river-fire.webp",
  },
  {
    "title": "Mona Tunnel",
    "url": "https://files.jacobsamo.com/photography/mona-tunnel.webp",
    "alt": "Mona Tunnel",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 148788,
    "fileName": "mona-tunnel.webp",
  },
  {
    "title": "Someone Taking A Photo Battlesandjams Jsamophotography",
    "url": "https://files.jacobsamo.com/photography/someone-taking-a-photo-battlesandjams-jsamophotography.webp",
    "alt": "Person filming Battles and Jams venue on smartphone",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 204838,
    "fileName": "someone-taking-a-photo-battlesandjams-jsamophotography.webp",
  },
  {
    "title": "Sparkerler Bike Wheel",
    "url": "https://files.jacobsamo.com/photography/sparkerler-bike-wheel.webp",
    "alt": "Spinning bike wheel with sparklers.",
    "width": 1828,
    "height": 2048,
    "aspectRatio": 0.89,
    "format": "webp",
    "fileSize": 219526,
    "fileName": "sparkerler-bike-wheel.webp",
  },
  {
    "title": "Storms Roll In Jsamo Photography",
    "url": "https://files.jacobsamo.com/photography/storms-roll-in-jsamo_photography.webp",
    "alt": "Storms rolling in across Stradbroke Island",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 125508,
    "fileName": "storms-roll-in-jsamo_photography.webp",
  },
  {
    "title": "Stadbroke Island Sunrise Jsamo Photography",
    "url": "https://files.jacobsamo.com/photography/stadbroke-island-sunrise-jsamo_photography.webp",
    "alt": "Stadbroke Island Sunrise over the ocean",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 255708,
    "fileName": "stadbroke-island-sunrise-jsamo_photography.webp",
  },
  {
    "title": "Tasmina Mushrooms",
    "url": "https://files.jacobsamo.com/photography/tasmina-mushrooms.webp",
    "alt": "Orange mushrooms growing on dark bark",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 90172,
    "fileName": "tasmina-mushrooms.webp",
  },
  {
    "title": "Todd Regenerative Trainging Center",
    "url": "https://files.jacobsamo.com/photography/tod-regenerative-trainging-center.webp",
    "alt": "Todd explaining regenerative training center tour",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 118520,
    "fileName": "tod-regenerative-trainging-center.webp",
  },
  {
    "title": "Venus Rising",
    "url": "https://files.jacobsamo.com/photography/Venus Rising.webp",
    "alt": "Illuminated tower sculpture at night",
    "width": 1365,
    "height": 2048,
    "aspectRatio": 0.67,
    "format": "webp",
    "fileSize": 206402,
    "fileName": "Venus Rising.webp",
  },
  {
    "title": "Wallaby Jsamo Photography",
    "url": "https://files.jacobsamo.com/photography/wallaby-jsamo_photography.webp",
    "alt": "Wallaby resting on coastal cliff",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 233004,
    "fileName": "wallaby-jsamo_photography.webp",
  },
  {
    "title": "White Haven Beach",
    "url": "https://files.jacobsamo.com/photography/white-haven-beach.webp",
    "alt": "Whitehaven beach Witsundays",
    "width": 2048,
    "height": 1206,
    "aspectRatio": 1.7,
    "format": "webp",
    "fileSize": 61456,
    "fileName": "white-haven-beach.webp",
  },
  {
    "title": "Walley Muralsbyedwin",
    "url": "https://files.jacobsamo.com/photography/walley-muralsbyedwin.webp",
    "alt": "Colorful mural of Wheres Walley character with paint roller",
    "width": 1663,
    "height": 2048,
    "aspectRatio": 0.81,
    "format": "webp",
    "fileSize": 183928,
    "fileName": "walley-muralsbyedwin.webp",
  },
  {
    "title": "Whitesundays",
    "url": "https://files.jacobsamo.com/photography/whitesundays.webp",
    "alt": "Sunset over the ocean Witsundays",
    "width": 2048,
    "height": 1365,
    "aspectRatio": 1.5,
    "format": "webp",
    "fileSize": 91542,
    "fileName": "whitesundays.webp",
  },
  {
    "title": "Wooden Star",
    "url": "https://files.jacobsamo.com/photography/wooden-star.webp",
    "alt": "Wooden star ornament with metal details.",
    "width": 1444,
    "height": 2048,
    "aspectRatio": 0.71,
    "format": "webp",
    "fileSize": 155590,
    "fileName": "wooden-star.webp",
  }
]

export default images;
