/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as LinksRouteImport } from './routes/links'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignIndexRouteImport } from './routes/design/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as DesignSlugRouteImport } from './routes/design/$slug'
import { Route as BlogPostIdRouteImport } from './routes/blog/$postId'

const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSlugRoute = DesignSlugRouteImport.update({
  id: '/design/$slug',
  path: '/design/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/photography': typeof PhotographyRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/design/$slug': typeof DesignSlugRoute
  '/blog': typeof BlogIndexRoute
  '/design': typeof DesignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/photography': typeof PhotographyRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/design/$slug': typeof DesignSlugRoute
  '/blog': typeof BlogIndexRoute
  '/design': typeof DesignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/photography': typeof PhotographyRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/design/$slug': typeof DesignSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/design/': typeof DesignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/links'
    | '/photography'
    | '/blog/$postId'
    | '/design/$slug'
    | '/blog'
    | '/design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/links'
    | '/photography'
    | '/blog/$postId'
    | '/design/$slug'
    | '/blog'
    | '/design'
  id:
    | '__root__'
    | '/'
    | '/links'
    | '/photography'
    | '/blog/$postId'
    | '/design/$slug'
    | '/blog/'
    | '/design/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinksRoute: typeof LinksRoute
  PhotographyRoute: typeof PhotographyRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  DesignSlugRoute: typeof DesignSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DesignIndexRoute: typeof DesignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$slug': {
      id: '/design/$slug'
      path: '/design/$slug'
      fullPath: '/design/$slug'
      preLoaderRoute: typeof DesignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinksRoute: LinksRoute,
  PhotographyRoute: PhotographyRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  DesignSlugRoute: DesignSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DesignIndexRoute: DesignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
